name: check-commit

on:
  - push
  - pull_request

jobs:
  check-commit:
    runs-on: macOS-11

    steps:
      - name: Use Xcode 13.1
        run: |
          sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer

      - name: Current platform versions
        run: |
          sw_vers
          xcodebuild -version
          swift --version
          swiftlint version

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Run lint
        run: |
          make lint

      - name: Run test
        run: |
          make test
